plugins {
    id "java"
    id "com.gtnewhorizons.retrofuturagradle" version "2.0.2"
}

version = project.modVersion
group = project.modGroup
base {
    archivesName = project.modBaseName
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(8)
    }
}

minecraft {
    mcVersion.set(project.minecraftVersion)
    mcpMappingChannel.set("stable")
    mcpMappingVersion.set("12")
    username.set("Developer")
    javaCompatibilityVersion.set(7)
    jvmLanguageVersion.set(JavaLanguageVersion.of(8))
}

repositories {
    maven {
        name = "GTNH Maven"
        url = uri("https://nexus.gtnewhorizons.com/repository/public/")
    }
    mavenCentral()
}

dependencies {
    compileOnly files("libs/BetterQuesting-3.7.15-GTNH-dev.jar")
}

tasks.withType(JavaCompile).configureEach {
    sourceCompatibility = "1.7"
    targetCompatibility = "1.7"
    options.compilerArgs << "-Xlint:-options"
}

tasks.processResources {
    inputs.property "version", project.version
    inputs.property "mcversion", project.minecraftVersion
    inputs.property "modid", project.modId
    inputs.property "modname", project.modName

    filesMatching("mcmod.info") {
        expand(
                "version": project.version,
                "mcversion": project.minecraftVersion,
                "modid": project.modId,
                "modname": project.modName
        )
    }
}

tasks.jar {
    manifest {
        attributes(
                "Implementation-Title": project.modName,
                "Implementation-Version": project.version
        )
    }
}
